// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdbyrjeyralxfxqrsrws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkYnlyamV5cmFseGZ4cXJzcndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzQ2MjEsImV4cCI6MjA2OTA1MDYyMX0.CLy6snj7Bg9JS12pnK2117egaJmyLAoIvcAAy1SykvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});